version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - "db-data:/var/lib/postgresql/data"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80

volumes:
  db-data: